ClientX: ClientX.App Class Reference
ClientX.App Class Reference
Logika interakcji dla klasy App.xaml
Public Member Functions
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Static Public Member Functions
static void Main ()
Application Entry Point.
static void Main ()
Application Entry Point.
Detailed Description
Logika interakcji dla klasy App.xaml
App
Definition at line 8 of file App.xaml.cs.
Member Function Documentation
InitializeComponent() [1/2]
void ClientX.App.InitializeComponent () inline
InitializeComponent
Definition at line 48 of file App.g.cs.
{
            #line 5 "..\..\App.xaml"
            this.StartupUri = new System.Uri("LoginWindow.xaml", System.UriKind.Relative);
            #line default
            #line hidden
        }
Referenced by ClientX.App.Main().
InitializeComponent() [2/2]
void ClientX.App.InitializeComponent () inline
InitializeComponent
Definition at line 48 of file App.g.i.cs.
{
            #line 5 "..\..\App.xaml"
            this.StartupUri = new System.Uri("LoginWindow.xaml", System.UriKind.Relative);
            #line default
            #line hidden
        }
Main() [1/2]
static void ClientX.App.Main () inline static
Application Entry Point.
Definition at line 63 of file App.g.cs.
{
            ClientX.App app = new ClientX.App();
            app.InitializeComponent();
            app.Run();
        }
References ClientX.App.InitializeComponent().
Main() [2/2]
static void ClientX.App.Main () inline static
Application Entry Point.
Definition at line 63 of file App.g.i.cs.
{
            ClientX.App app = new ClientX.App();
            app.InitializeComponent();
            app.Run();
        }
References ClientX.App.InitializeComponent().
The documentation for this class was generated from the following files:
App.xaml.cs
obj/Debug/App.g.cs
obj/Debug/App.g.i.cs