ClientX: ClientX.LoginWindow Class Reference
ClientX.LoginWindow Class Reference
Logika interakcji dla klasy LoginWindow.xaml
Public Member Functions
LoginWindow ()
Inicjalizacja komponentu
bool checkCredentials (string username, string userpassword)
Walidacja poprawności danych logowania
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Private Member Functions
void tryLogin (object sender, RoutedEventArgs e)
Funkcja sprawdza czy oba pola logowania są wypełnione i zwraca komunikat do użytkownika, gdy ich nie wypełnił. Następnie wywołuje funkcje która waliduje poprawność wpisanych danych logowania, i jeśli są poprawne to inicjalizuje główne okno aplikacji lub jeśli nie są, wyświetla komunikat o błędzie.
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
readonly string user = "user"
readonly string userPassword = "user"
bool _contentLoaded
Detailed Description
Logika interakcji dla klasy LoginWindow.xaml
LoginWindow
Definition at line 9 of file LoginWindow.xaml.cs.
Constructor & Destructor Documentation
LoginWindow()
ClientX.LoginWindow.LoginWindow () inline
Inicjalizacja komponentu
InitializeComponent(); Inicjalizacja
Definition at line 22 of file LoginWindow.xaml.cs.
        {
            InitializeComponent();
        }
References ClientX.LoginWindow.InitializeComponent().
Member Function Documentation
checkCredentials()
bool ClientX.LoginWindow.checkCredentials (string username, string userpassword) inline
Walidacja poprawności danych logowania
Parameters
username Login podany przez użytkownika
userpassword Hasło podane przez użytkownika
Returns
bool validated - Zwraca True jeśli dane się zgadzają
Definition at line 32 of file LoginWindow.xaml.cs.
        {
            bool validated = false;
            if (username == user && userpassword == userPassword)
            {
                validated = true;
            }
            return validated;
        }
References ClientX.LoginWindow.user, and ClientX.LoginWindow.userPassword.
Referenced by ClientXTestes.LoginWindowTests.TestLoginValidation(), and ClientX.LoginWindow.tryLogin().
Connect() [1/2]
void System.Windows.Markup.IComponentConnector. ClientX.LoginWindow.Connect (int connectionId, object target) inline private
Definition at line 94 of file LoginWindow.g.cs.
{
            switch (connectionId)
            {
            case 1:
            this.LoginInput = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.PasswordInput = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 3:
            this.btnSubmit = ((System.Windows.Controls.Button)(target));
            #line 17 "..\..\LoginWindow.xaml"
            this.btnSubmit.Click += new System.Windows.RoutedEventHandler(this.tryLogin);
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
References ClientX.LoginWindow.tryLogin().
Connect() [2/2]
void System.Windows.Markup.IComponentConnector. ClientX.LoginWindow.Connect (int connectionId, object target) inline private
Definition at line 94 of file LoginWindow.g.i.cs.
{
            switch (connectionId)
            {
            case 1:
            this.LoginInput = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.PasswordInput = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 3:
            this.btnSubmit = ((System.Windows.Controls.Button)(target));
            #line 17 "..\..\LoginWindow.xaml"
            this.btnSubmit.Click += new System.Windows.RoutedEventHandler(this.tryLogin);
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
References ClientX.LoginWindow.tryLogin().
InitializeComponent() [1/2]
void ClientX.LoginWindow.InitializeComponent () inline
InitializeComponent
Definition at line 74 of file LoginWindow.g.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/loginwindow.xaml", System.UriKind.Relative);
            #line 1 "..\..\LoginWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.LoginWindow._contentLoaded.
Referenced by ClientX.LoginWindow.LoginWindow().
InitializeComponent() [2/2]
void ClientX.LoginWindow.InitializeComponent () inline
InitializeComponent
Definition at line 74 of file LoginWindow.g.i.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/loginwindow.xaml", System.UriKind.Relative);
            #line 1 "..\..\LoginWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.LoginWindow._contentLoaded.
tryLogin()
void ClientX.LoginWindow.tryLogin (object sender, RoutedEventArgs e) inline private
Funkcja sprawdza czy oba pola logowania są wypełnione i zwraca komunikat do użytkownika, gdy ich nie wypełnił. Następnie wywołuje funkcje która waliduje poprawność wpisanych danych logowania, i jeśli są poprawne to inicjalizuje główne okno aplikacji lub jeśli nie są, wyświetla komunikat o błędzie.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event Executed wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 49 of file LoginWindow.xaml.cs.
        {
            if (LoginInput.Text.Length == 0)
            {
                MessageBox.Show("Please enter the username.");
                LoginInput.Focus();
            }
            if (PasswordInput.Password.Length == 0)
            {
                MessageBox.Show("Please enter the password.");
                PasswordInput.Focus();
            }
            bool validated = checkCredentials(LoginInput.Text, PasswordInput.Password);
            if (validated)
            {
                MainWindow mw = new MainWindow();
                mw.Show();
                Close();
            }
            else
            {
                MessageBox.Show("Your credentials are incorrect! Try again");
            }
        }
References ClientX.LoginWindow.checkCredentials().
Referenced by ClientX.LoginWindow.Connect().
Field Documentation
_contentLoaded
bool ClientX.LoginWindow._contentLoaded private
Definition at line 67 of file LoginWindow.g.cs.
Referenced by ClientX.LoginWindow.InitializeComponent().
user
readonly string ClientX.LoginWindow.user = "user" private
a public variable. Details.
Definition at line 15 of file LoginWindow.xaml.cs.
Referenced by ClientX.LoginWindow.checkCredentials().
userPassword
readonly string ClientX.LoginWindow.userPassword = "user" private
Definition at line 16 of file LoginWindow.xaml.cs.
Referenced by ClientX.LoginWindow.checkCredentials().
The documentation for this class was generated from the following files:
LoginWindow.xaml.cs
obj/Debug/LoginWindow.g.cs
obj/Debug/LoginWindow.g.i.cs