ClientX: ClientX.MainWindow Class Reference
ClientX.MainWindow Class Reference
Logika interakcji dla klasy MainWindow.xaml
Public Member Functions
MainWindow ()
Inicjalizacja głównego okna aplikacji
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Data Fields
Dashboard dp = new Dashboard()
Przypisanie i inicjalizacja strony Dashboard
Dashboard dpNew
Zmienna pomocnicza do sprawdzenia czy strona Dashboard zotała wcześniej zainicjalizowana
Private Member Functions
void Window_Loaded (object sender, RoutedEventArgs e)
Funkcja wywoływana po załadowaniu okna, która przypisuje strone Dashboard do zawartości Frame.
void showDashboardHandler (object sender, RoutedEventArgs e)
Funkcja odpowiadająca za sprawdzenie, czy wcześniej strona Dashboard została zainicjalizowana oraz za załadowanie tej strony do główneg Frame aplikacji.
void exitAppHandler (object sender, RoutedEventArgs e)
Metoda odpowiadająca za zamknięcie okna aplikacji.
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
bool _contentLoaded
Detailed Description
Logika interakcji dla klasy MainWindow.xaml
MainWindow
Definition at line 9 of file MainWindow.xaml.cs.
Constructor & Destructor Documentation
MainWindow()
ClientX.MainWindow.MainWindow () inline
Inicjalizacja głównego okna aplikacji
Definition at line 24 of file MainWindow.xaml.cs.
        {
            InitializeComponent();
        }
References ClientX.MainWindow.InitializeComponent().
Member Function Documentation
Connect() [1/2]
void System.Windows.Markup.IComponentConnector. ClientX.MainWindow.Connect (int connectionId, object target) inline private
Definition at line 78 of file MainWindow.g.cs.
{
            switch (connectionId)
            {
            case 1:
            #line 8 "..\..\MainWindow.xaml"
            ((ClientX.MainWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            #line default
            #line hidden
            return;
            case 2:
            #line 27 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.showDashboardHandler);
            #line default
            #line hidden
            return;
            case 3:
            #line 28 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.exitAppHandler);
            #line default
            #line hidden
            return;
            case 4:
            this.MainFrame = ((System.Windows.Controls.Frame)(target));
            return;
            }
            this._contentLoaded = true;
        }
Connect() [2/2]
void System.Windows.Markup.IComponentConnector. ClientX.MainWindow.Connect (int connectionId, object target) inline private
Definition at line 78 of file MainWindow.g.i.cs.
{
            switch (connectionId)
            {
            case 1:
            #line 8 "..\..\MainWindow.xaml"
            ((ClientX.MainWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            #line default
            #line hidden
            return;
            case 2:
            #line 27 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.showDashboardHandler);
            #line default
            #line hidden
            return;
            case 3:
            #line 28 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.exitAppHandler);
            #line default
            #line hidden
            return;
            case 4:
            this.MainFrame = ((System.Windows.Controls.Frame)(target));
            return;
            }
            this._contentLoaded = true;
        }
exitAppHandler()
void ClientX.MainWindow.exitAppHandler (object sender, RoutedEventArgs e) inline private
Metoda odpowiadająca za zamknięcie okna aplikacji.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event wskazuje na zdarzenie, które jest kierowane
Definition at line 69 of file MainWindow.xaml.cs.
        {
            Close();
        }
InitializeComponent() [1/2]
void ClientX.MainWindow.InitializeComponent () inline
InitializeComponent
Definition at line 58 of file MainWindow.g.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/mainwindow.xaml", System.UriKind.Relative);
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.MainWindow._contentLoaded.
Referenced by ClientX.MainWindow.MainWindow().
InitializeComponent() [2/2]
void ClientX.MainWindow.InitializeComponent () inline
InitializeComponent
Definition at line 58 of file MainWindow.g.i.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/mainwindow.xaml", System.UriKind.Relative);
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.MainWindow._contentLoaded.
showDashboardHandler()
void ClientX.MainWindow.showDashboardHandler (object sender, RoutedEventArgs e) inline private
Funkcja odpowiadająca za sprawdzenie, czy wcześniej strona Dashboard została zainicjalizowana oraz za załadowanie tej strony do główneg Frame aplikacji.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event wskazuje na zdarzenie, które jest kierowane
Definition at line 44 of file MainWindow.xaml.cs.
        {
            if (dp != null)
            {
                MainFrame.Content = dp;
            }
            else
            {
                if (this.dpNew != null)
                {
                    MainFrame.Content = this.dpNew;
                }
                else
                {
                    this.dpNew = new Dashboard();
                }
            }
        }
References ClientX.MainWindow.dp, and ClientX.MainWindow.dpNew.
Window_Loaded()
void ClientX.MainWindow.Window_Loaded (object sender, RoutedEventArgs e) inline private
Funkcja wywoływana po załadowaniu okna, która przypisuje strone Dashboard do zawartości Frame.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event wskazuje na zdarzenie, które jest kierowane
Definition at line 34 of file MainWindow.xaml.cs.
        {
            MainFrame.Content = this.dp;
        }
References ClientX.MainWindow.dp.
Field Documentation
_contentLoaded
bool ClientX.MainWindow._contentLoaded private
Definition at line 51 of file MainWindow.g.cs.
Referenced by ClientX.MainWindow.InitializeComponent().
dp
Dashboard ClientX.MainWindow.dp = new Dashboard()
Przypisanie i inicjalizacja strony Dashboard
Definition at line 14 of file MainWindow.xaml.cs.
Referenced by ClientX.MainWindow.showDashboardHandler(), and ClientX.MainWindow.Window_Loaded().
dpNew
Dashboard ClientX.MainWindow.dpNew
Zmienna pomocnicza do sprawdzenia czy strona Dashboard zotała wcześniej zainicjalizowana
Definition at line 19 of file MainWindow.xaml.cs.
Referenced by ClientX.MainWindow.showDashboardHandler().
The documentation for this class was generated from the following files:
MainWindow.xaml.cs
obj/Debug/MainWindow.g.cs
obj/Debug/MainWindow.g.i.cs