ClientX: ClientX.Dashboard Class Reference
ClientX.Dashboard Class Reference
Logika interakcji dla klasy Dashboard.xaml
Public Member Functions
Dashboard ()
Załadowanie strony panelu głównego oraz przypisanie zasobów do zmiennych.
System.Windows.Forms.DialogResult ShowDialogBox (string message)
Funkcja pomocnicza, która pozwala na wyświetlenie monitu użytkownikowi.
decimal? ValidateFreight (string freight)
Funkcja odpowiadająca za walidację pola Freight oraz konwersję na liczbę dziesiętną
void Delete_Order (Orders order, string type="single")
Metoda, która odpowiada za usuwanie zamówień z bazy. Wywoływana jest przy usuwaniu pojedynczego zamówienia oraz podczas usuwania klienta z bazy - wtedy usuwa wszystkie zamówienia przypisane do danego klienta.
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Static Public Member Functions
static System.Windows.Forms.DialogResult ShowDeleteDialog (string message="Are you sure to delete row?")
Funkcja pomocnicza, pokazująca monit użytkownikowi z możliwością potwierdzenia lub anulowania operacji usuwania.
Properties
static System.Windows.Forms.DialogResult ShowAbortMessage [get]
Funkcja pomocnicza, pokazująca monit użytkownikowi o anulowaniu wykonywanej operacji
Private Member Functions
void Page_Loaded (object sender, RoutedEventArgs e)
Odnalezienie źródła danych i wyświetlenie go.
void LastCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda przenosząca nas do ostatniego elementu bazy danych.
void PreviousCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda przenosząca nas do poprzedniego elementu bazy danych po naciśnięciu przycisku
void NextCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda przenosząca nas do następnego elementu bazy danych po wciśnięciu przycisku.
void FirstCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda przenosząca nas do pierwszego elementu bazy danych po naciśnięciu przycisku.
void Search (object sender, ExecutedRoutedEventArgs e)
Metoda przenosząca nas do elementu wyszukanego po danym przez użytkownika CustomerID. Metoda wyciąga tekst, który użytkownik wpisał w wyszukiwarke a następnie przenosi nas do rekordu bazy, w którym pole CustomerID jest takie samo
void UpdateCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda ta odpowiada za dwa zdarzenia. Dodanie nowego klienta oraz dodanie nowego zamówienia w zależności od widoczności danego formularza. Przy dodawaniu nowego klienta, metoda sprawdza czy pole CustomerID jest wypełnione, jeśli tak to dodaje rekord na ostatnie miejsce w bazie. W przypadku dodawania nowego zamówienia, metoda waliduje pole Freight i EmployeeID a następnie dodaje rekord do bazy.
void AddCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda odwołująca się do przycisku Add, która wywołuje Grid dla dodania nowego klienta, czyści jego pola oraz ukrywa inny aktualnie otworzony formularz.
void NewOrder_click (object sender, RoutedEventArgs e)
Metoda odwołująca się do przycisku Add, która sprawdza czy wybrany jest klient do którego ma być dopisane zamówienie a następnie ukrywa inne formularze i wyświetla formularz dodania nowego zamówienia.
void DeleteCustomerCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda odpowiadająca za usunięcie użytkownik z bazy oraz usunięcie wszystkich jego zamówień.
void CancelCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda odpowiadająca za anulowanie wprowadzania nowego klienta.
void DeleteOrderCommandHandler (object sender, ExecutedRoutedEventArgs e)
Metoda, przypisana do kontrolki, która wywołuję funkcję usuwająca zamówienia z bazy.
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
DatabaseEntities context = new DatabaseEntities()
CollectionViewSource customerViewSource
CollectionViewSource ordViewSource
bool _contentLoaded
Detailed Description
Logika interakcji dla klasy Dashboard.xaml
Dashboard
Definition at line 15 of file Dashboard.xaml.cs.
Constructor & Destructor Documentation
Dashboard()
ClientX.Dashboard.Dashboard () inline
Załadowanie strony panelu głównego oraz przypisanie zasobów do zmiennych.
InitializeComponent(); Inicjalizacja głównego okna
Definition at line 27 of file Dashboard.xaml.cs.
        {
            InitializeComponent();
            customerViewSource = (CollectionViewSource)FindResource("customersViewSource");
            ordViewSource = (CollectionViewSource)FindResource("customersOrdersViewSource");
            DataContext = this;
        }
References ClientX.Dashboard.customerViewSource, ClientX.Dashboard.InitializeComponent(), and ClientX.Dashboard.ordViewSource.
Member Function Documentation
AddCommandHandler()
void ClientX.Dashboard.AddCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda odwołująca się do przycisku Add, która wywołuje Grid dla dodania nowego klienta, czyści jego pola oraz ukrywa inny aktualnie otworzony formularz.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 242 of file Dashboard.xaml.cs.
        {
            existingCustomerGrid.Visibility = Visibility.Collapsed;
            newOrderGrid.Visibility = Visibility.Collapsed;
            newCustomerGrid.Visibility = Visibility.Visible;
            foreach (var child in newCustomerGrid.Children)
            {
                var tb = child as TextBox;
                if (tb != null)
                {
                    tb.Text = "";
                }
            }
        }
CancelCommandHandler()
void ClientX.Dashboard.CancelCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda odpowiadająca za anulowanie wprowadzania nowego klienta.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 403 of file Dashboard.xaml.cs.
        {
            add_addressTextBox.Text = "";
            add_cityTextBox.Text = "";
            add_companyNameTextBox.Text = "";
            add_contactNameTextBox.Text = "";
            add_contactTitleTextBox.Text = "";
            add_countryTextBox.Text = "";
            add_customerIDTextBox.Text = "";
            add_phoneTextBox.Text = "";
            add_postalCodeTextBox.Text = "";
            add_regionTextBox.Text = "";
            newOrderGrid.Visibility = Visibility.Collapsed;
            newCustomerGrid.Visibility = Visibility.Collapsed;
            existingCustomerGrid.Visibility = Visibility.Visible;
        }
Connect() [1/2]
void System.Windows.Markup.IComponentConnector. ClientX.Dashboard.Connect (int connectionId, object target) inline private
Definition at line 462 of file Dashboard.g.cs.
{
            switch (connectionId)
            {
            case 1:
            #line 9 "..\..\Dashboard.xaml"
            ((ClientX.Dashboard)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            #line default
            #line hidden
            return;
            case 2:
            #line 82 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.FirstCommandHandler);
            #line default
            #line hidden
            return;
            case 3:
            #line 83 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.LastCommandHandler);
            #line default
            #line hidden
            return;
            case 4:
            #line 84 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.NextCommandHandler);
            #line default
            #line hidden
            return;
            case 5:
            #line 85 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.PreviousCommandHandler);
            #line default
            #line hidden
            return;
            case 6:
            #line 86 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteOrderCommandHandler);
            #line default
            #line hidden
            return;
            case 7:
            #line 87 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.UpdateCommandHandler);
            #line default
            #line hidden
            return;
            case 8:
            #line 88 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.AddCommandHandler);
            #line default
            #line hidden
            return;
            case 9:
            #line 89 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteCustomerCommandHandler);
            #line default
            #line hidden
            return;
            case 10:
            #line 90 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.UpdateCommandHandler);
            #line default
            #line hidden
            return;
            case 11:
            #line 91 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.AddCommandHandler);
            #line default
            #line hidden
            return;
            case 12:
            #line 92 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CancelCommandHandler);
            #line default
            #line hidden
            return;
            case 13:
            #line 93 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.Search);
            #line default
            #line hidden
            return;
            case 14:
            this.btnFirst = ((System.Windows.Controls.Button)(target));
            return;
            case 15:
            this.btnPrev = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.btnLast = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.btnNewOrder = ((System.Windows.Controls.Button)(target));
            #line 109 "..\..\Dashboard.xaml"
            this.btnNewOrder.Click += new System.Windows.RoutedEventHandler(this.NewOrder_click);
            #line default
            #line hidden
            return;
            case 21:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            return;
            case 22:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            return;
            case 23:
            this.search_id = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.btnMove = ((System.Windows.Controls.Button)(target));
            return;
            case 25:
            this.existingCustomerGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.customerIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.companyNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.contactNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.contactTitleTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.addressTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.cityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.countryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.phoneTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.postalCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.regionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            this.newCustomerGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.add_customerIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.add_companyNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.add_contactNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 40:
            this.add_contactTitleTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 41:
            this.add_addressTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 42:
            this.add_cityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 43:
            this.add_countryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 44:
            this.add_phoneTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 45:
            this.add_postalCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.add_regionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 47:
            this.newOrderGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.add_employeeIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 49:
            this.add_orderDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 50:
            this.add_ShipViaTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.add_freightTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 52:
            this.ordersDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 53:
            this.customerIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 54:
            this.employeeIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 55:
            this.freightColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 56:
            this.orderIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 57:
            this.shipAddressColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 58:
            this.shipCityColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 59:
            this.shipCountryColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 60:
            this.shipNameColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 61:
            this.shipPostalCodeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 62:
            this.shipRegionColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
References ClientX.Dashboard.NewOrder_click().
Connect() [2/2]
void System.Windows.Markup.IComponentConnector. ClientX.Dashboard.Connect (int connectionId, object target) inline private
Definition at line 462 of file Dashboard.g.i.cs.
{
            switch (connectionId)
            {
            case 1:
            #line 9 "..\..\Dashboard.xaml"
            ((ClientX.Dashboard)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            #line default
            #line hidden
            return;
            case 2:
            #line 82 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.FirstCommandHandler);
            #line default
            #line hidden
            return;
            case 3:
            #line 83 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.LastCommandHandler);
            #line default
            #line hidden
            return;
            case 4:
            #line 84 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.NextCommandHandler);
            #line default
            #line hidden
            return;
            case 5:
            #line 85 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.PreviousCommandHandler);
            #line default
            #line hidden
            return;
            case 6:
            #line 86 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteOrderCommandHandler);
            #line default
            #line hidden
            return;
            case 7:
            #line 87 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.UpdateCommandHandler);
            #line default
            #line hidden
            return;
            case 8:
            #line 88 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.AddCommandHandler);
            #line default
            #line hidden
            return;
            case 9:
            #line 89 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.DeleteCustomerCommandHandler);
            #line default
            #line hidden
            return;
            case 10:
            #line 90 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.UpdateCommandHandler);
            #line default
            #line hidden
            return;
            case 11:
            #line 91 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.AddCommandHandler);
            #line default
            #line hidden
            return;
            case 12:
            #line 92 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.CancelCommandHandler);
            #line default
            #line hidden
            return;
            case 13:
            #line 93 "..\..\Dashboard.xaml"
            ((System.Windows.Input.CommandBinding)(target)).Executed += new System.Windows.Input.ExecutedRoutedEventHandler(this.Search);
            #line default
            #line hidden
            return;
            case 14:
            this.btnFirst = ((System.Windows.Controls.Button)(target));
            return;
            case 15:
            this.btnPrev = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.btnNext = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.btnLast = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.btnDelete = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btnAdd = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.btnNewOrder = ((System.Windows.Controls.Button)(target));
            #line 109 "..\..\Dashboard.xaml"
            this.btnNewOrder.Click += new System.Windows.RoutedEventHandler(this.NewOrder_click);
            #line default
            #line hidden
            return;
            case 21:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            return;
            case 22:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            return;
            case 23:
            this.search_id = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.btnMove = ((System.Windows.Controls.Button)(target));
            return;
            case 25:
            this.existingCustomerGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.customerIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.companyNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.contactNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.contactTitleTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.addressTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.cityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.countryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.phoneTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.postalCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.regionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            this.newCustomerGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.add_customerIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.add_companyNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.add_contactNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 40:
            this.add_contactTitleTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 41:
            this.add_addressTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 42:
            this.add_cityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 43:
            this.add_countryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 44:
            this.add_phoneTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 45:
            this.add_postalCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.add_regionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 47:
            this.newOrderGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.add_employeeIDTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 49:
            this.add_orderDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 50:
            this.add_ShipViaTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.add_freightTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 52:
            this.ordersDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 53:
            this.customerIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 54:
            this.employeeIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 55:
            this.freightColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 56:
            this.orderIDColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 57:
            this.shipAddressColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 58:
            this.shipCityColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 59:
            this.shipCountryColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 60:
            this.shipNameColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 61:
            this.shipPostalCodeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 62:
            this.shipRegionColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
References ClientX.Dashboard.NewOrder_click().
Delete_Order()
void ClientX.Dashboard.Delete_Order (Orders order, string type = "single") inline
Metoda, która odpowiada za usuwanie zamówień z bazy. Wywoływana jest przy usuwaniu pojedynczego zamówienia oraz podczas usuwania klienta z bazy - wtedy usuwa wszystkie zamówienia przypisane do danego klienta.
Parameters
order Obiekt "Zamówienia" - może być to pojedyncze zamówienie lub zbiór zamówień
type Typ operacji jaka ma być wykonana - pojedyncze usunięcie lub usunięcie wszystkich zamówień klienta. Domyślnie usuwa pojedyncze zamówienie
Definition at line 283 of file Dashboard.xaml.cs.
        {
            var ord = (from o in context.Orders.Local
                       where o.OrderID == order.OrderID
                       select o).FirstOrDefault();
            if (type == "single")
            {
                System.Windows.Forms.DialogResult confirmation = ShowDeleteDialog();
                if (confirmation == System.Windows.Forms.DialogResult.Yes)
                {
                    try
                    {
                        foreach (var detail in ord.Order_Details.ToList())
{
                            context.Order_Details.Remove(detail);
                        }
                        context.Orders.Remove(ord);
                        context.SaveChanges();
                        ordViewSource.View.Refresh();
                        ShowDialogBox("Order deleted succesfully.");
                    }
                    catch (Exception error)
                    {
                        ShowDialogBox("Something went wrong. Error: " + error);
                    }
                }
                else
                {
                    _ = ShowAbortMessage;
                }
            }
            if (type == "all")
            {
                try
                {
                    foreach (var detail in ord.Order_Details.ToList())
                    {
                        context.Order_Details.Remove(detail);
                    }
                    context.Orders.Remove(ord);
                    context.SaveChanges();
                    ordViewSource.View.Refresh();
                }
                catch (Exception error)
                {
                    ShowDialogBox("Something went wrong. Error: " + error);
                }
            }
        }
References ClientX.Dashboard.context, ClientX.DatabaseEntities.Order_Details, ClientX.Orders.OrderID, ClientX.DatabaseEntities.Orders, ClientX.Dashboard.ordViewSource, ClientX.Dashboard.ShowAbortMessage, ClientX.Dashboard.ShowDeleteDialog(), and ClientX.Dashboard.ShowDialogBox().
Referenced by ClientX.Dashboard.DeleteCustomerCommandHandler(), and ClientX.Dashboard.DeleteOrderCommandHandler().
DeleteCustomerCommandHandler()
void ClientX.Dashboard.DeleteCustomerCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda odpowiadająca za usunięcie użytkownik z bazy oraz usunięcie wszystkich jego zamówień.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 354 of file Dashboard.xaml.cs.
        {
            var cur = customerViewSource.View.CurrentItem as Customers;
            var cust = (from c in context.Customers
                        where c.CustomerID == cur.CustomerID
                        select c).FirstOrDefault();
            if(cust != null)
            {
            }
            if (ShowDeleteDialog() == System.Windows.Forms.DialogResult.Yes
                && ShowDeleteDialog("Are you willing to delete all orders associated with this customer?") == System.Windows.Forms.DialogResult.Yes)
            {
              if (cust != null)
                {
                  try
                    {
                        foreach (var ord in cust.Orders.ToList())
{
                            Delete_Order(ord, "all");
                        }
                    }
                    catch (Exception error)
                    {
                         throw error;
                    }
                    ShowDialogBox("Customer and all his orders deleted succesfully.");
                    context.Customers.Remove(cust);
                }
                context.SaveChanges();
                customerViewSource.View.Refresh();
            }
            else
            {
                _ = ShowAbortMessage;
            }
        }
References ClientX.Dashboard.context, ClientX.DatabaseEntities.Customers, ClientX.Dashboard.customerViewSource, ClientX.Dashboard.Delete_Order(), ClientX.Dashboard.ShowAbortMessage, ClientX.Dashboard.ShowDeleteDialog(), and ClientX.Dashboard.ShowDialogBox().
DeleteOrderCommandHandler()
void ClientX.Dashboard.DeleteOrderCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda, przypisana do kontrolki, która wywołuję funkcję usuwająca zamówienia z bazy.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 429 of file Dashboard.xaml.cs.
        {
            Orders obj = e.Parameter as Orders;
            Delete_Order(obj);
        }
References ClientX.Dashboard.Delete_Order().
FirstCommandHandler()
void ClientX.Dashboard.FirstCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda przenosząca nas do pierwszego elementu bazy danych po naciśnięciu przycisku.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 102 of file Dashboard.xaml.cs.
        {
            customerViewSource.View.MoveCurrentToFirst();
        }
References ClientX.Dashboard.customerViewSource.
InitializeComponent() [1/2]
void ClientX.Dashboard.InitializeComponent () inline
InitializeComponent
Definition at line 442 of file Dashboard.g.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/dashboard.xaml", System.UriKind.Relative);
            #line 1 "..\..\Dashboard.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.Dashboard._contentLoaded.
Referenced by ClientX.Dashboard.Dashboard().
InitializeComponent() [2/2]
void ClientX.Dashboard.InitializeComponent () inline
InitializeComponent
Definition at line 442 of file Dashboard.g.i.cs.
{
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ClientX;component/dashboard.xaml", System.UriKind.Relative);
            #line 1 "..\..\Dashboard.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            #line default
            #line hidden
        }
References ClientX.Dashboard._contentLoaded.
LastCommandHandler()
void ClientX.Dashboard.LastCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda przenosząca nas do ostatniego elementu bazy danych.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 71 of file Dashboard.xaml.cs.
        {
            customerViewSource.View.MoveCurrentToLast();
        }
References ClientX.Dashboard.customerViewSource.
NewOrder_click()
void ClientX.Dashboard.NewOrder_click (object sender, RoutedEventArgs e) inline private
Metoda odwołująca się do przycisku Add, która sprawdza czy wybrany jest klient do którego ma być dopisane zamówienie a następnie ukrywa inne formularze i wyświetla formularz dodania nowego zamówienia.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event wskazuje na zdarzenie, które jest kierowane
Definition at line 263 of file Dashboard.xaml.cs.
        {
            var cust = customerViewSource.View.CurrentItem as Customers;
            if (cust == null)
            {
                MessageBox.Show("No customer selected.");
                return;
            }
            existingCustomerGrid.Visibility = Visibility.Collapsed;
            newCustomerGrid.Visibility = Visibility.Collapsed;
            newOrderGrid.UpdateLayout();
            newOrderGrid.Visibility = Visibility.Visible;
        }
References ClientX.Dashboard.customerViewSource.
Referenced by ClientX.Dashboard.Connect().
NextCommandHandler()
void ClientX.Dashboard.NextCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda przenosząca nas do następnego elementu bazy danych po wciśnięciu przycisku.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 91 of file Dashboard.xaml.cs.
        {
            customerViewSource.View.MoveCurrentToNext();
        }
References ClientX.Dashboard.customerViewSource.
Page_Loaded()
void ClientX.Dashboard.Page_Loaded (object sender, RoutedEventArgs e) inline private
Odnalezienie źródła danych i wyświetlenie go.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e Routed Event wskazuje na zdarzenie, które jest kierowane
context.Products.Load()
Załadowanie bazy produktów
Definition at line 41 of file Dashboard.xaml.cs.
        {
            context.Customers.Load();
            customerViewSource.Source = context.Customers.Local;
        }
References ClientX.Dashboard.context, ClientX.DatabaseEntities.Customers, and ClientX.Dashboard.customerViewSource.
PreviousCommandHandler()
void ClientX.Dashboard.PreviousCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda przenosząca nas do poprzedniego elementu bazy danych po naciśnięciu przycisku
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 81 of file Dashboard.xaml.cs.
        {
            customerViewSource.View.MoveCurrentToPrevious();
        }
References ClientX.Dashboard.customerViewSource.
Search()
void ClientX.Dashboard.Search (object sender, ExecutedRoutedEventArgs e) inline private
Metoda przenosząca nas do elementu wyszukanego po danym przez użytkownika CustomerID. Metoda wyciąga tekst, który użytkownik wpisał w wyszukiwarke a następnie przenosi nas do rekordu bazy, w którym pole CustomerID jest takie samo
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
context.Customers.Where(x => x.CustomerID.Contains(Search)).FirstOrDefault()
Znalazienie rekordu o odpowiadającym CustomerID
Definition at line 117 of file Dashboard.xaml.cs.
        {
            TextBox txtb = (TextBox)search_id;
            string Search = search_id.Text;
            customerViewSource.View.MoveCurrentTo(context.Customers.Where(x => x.CustomerID.Contains(Search)).FirstOrDefault());
        }
References ClientX.Dashboard.context, ClientX.DatabaseEntities.Customers, ClientX.Dashboard.customerViewSource, and ClientX.Dashboard.Search().
Referenced by ClientX.Dashboard.Search().
ShowDeleteDialog()
static System.Windows.Forms.DialogResult ClientX.Dashboard.ShowDeleteDialog (string message = "Are you sure to delete row?") static
Funkcja pomocnicza, pokazująca monit użytkownikowi z możliwością potwierdzenia lub anulowania operacji usuwania.
Referenced by ClientX.Dashboard.Delete_Order(), and ClientX.Dashboard.DeleteCustomerCommandHandler().
ShowDialogBox()
System.Windows.Forms.DialogResult ClientX.Dashboard.ShowDialogBox (string message) inline
Funkcja pomocnicza, która pozwala na wyświetlenie monitu użytkownikowi.
Parameters
message Wiadomośc, która ma się wyświetlić w monicie
Definition at line 62 of file Dashboard.xaml.cs.
        {
            return MessageBox.Show(message);
        }
Referenced by ClientX.Dashboard.Delete_Order(), and ClientX.Dashboard.DeleteCustomerCommandHandler().
UpdateCommandHandler()
void ClientX.Dashboard.UpdateCommandHandler (object sender, ExecutedRoutedEventArgs e) inline private
Metoda ta odpowiada za dwa zdarzenia. Dodanie nowego klienta oraz dodanie nowego zamówienia w zależności od widoczności danego formularza. Przy dodawaniu nowego klienta, metoda sprawdza czy pole CustomerID jest wypełnione, jeśli tak to dodaje rekord na ostatnie miejsce w bazie. W przypadku dodawania nowego zamówienia, metoda waliduje pole Freight i EmployeeID a następnie dodaje rekord do bazy.
Parameters
sender Parametr sender zawiera odniesienie do kontrolki/obiektu, który wywołał zdarzenie
e ExecutedRouted Event wskazuje na zdarzenie, które jest kierowane i wykonane
Definition at line 153 of file Dashboard.xaml.cs.
        {
            if (newCustomerGrid.IsVisible)
            {
                Customers newCustomer = new Customers
                {
                    Address = add_addressTextBox.Text,
                    City = add_cityTextBox.Text,
                    CompanyName = add_companyNameTextBox.Text,
                    ContactName = add_contactNameTextBox.Text,
                    ContactTitle = add_contactTitleTextBox.Text,
                    Country = add_countryTextBox.Text,
                    CustomerID = add_customerIDTextBox.Text,
                    Phone = add_phoneTextBox.Text,
                    PostalCode = add_postalCodeTextBox.Text,
                    Region = add_regionTextBox.Text
                };
                if (newCustomer.CustomerID.Length != 0)
                {
                    int len = context.Customers.Local.Count();
                    int pos = len;
                    for (int i = 0; i < len; ++i)
                    {
                        if (String.CompareOrdinal(newCustomer.CustomerID, context.Customers.Local[i].CustomerID) < 0)
{
                            pos = i;
                            break;
                        }
                    }
                    context.Customers.Local.Insert(pos, newCustomer);
                    customerViewSource.View.Refresh();
                    customerViewSource.View.MoveCurrentTo(newCustomer);
                }
                else
                {
                    MessageBox.Show("CustomerID cannot be null");
                }
                newCustomerGrid.Visibility = Visibility.Collapsed;
                existingCustomerGrid.Visibility = Visibility.Visible;
            }
            else if (newOrderGrid.IsVisible)
            {
                Customers currentCustomer = (Customers)customerViewSource.View.CurrentItem;
                Orders newOrder = new Orders()
                {
                    OrderDate = add_orderDatePicker.SelectedDate,
                    CustomerID = currentCustomer.CustomerID,
                    ShipAddress = currentCustomer.Address,
                    ShipCity = currentCustomer.City,
                    ShipCountry = currentCustomer.Country,
                    ShipName = currentCustomer.CompanyName,
                    ShipPostalCode = currentCustomer.PostalCode,
                    ShipRegion = currentCustomer.Region
                };
                try
                {
                    newOrder.EmployeeID = Int32.Parse(add_employeeIDTextBox.Text);
                }
                catch
                {
                    MessageBox.Show("EmployeeID must be a valid integer value.");
                    return;
                }
                try
                {
                    newOrder.Freight = ValidateFreight(add_freightTextBox.Text);
                }
                catch
                {
                    MessageBox.Show("Freight must be convertible to decimal and greater than 1.");
                    return;
                }
                context.Orders.Add(newOrder);
                ordViewSource.View.Refresh();
            }
            context.SaveChanges();
        }
References ClientX.Customers.Address, ClientX.Customers.City, ClientX.Customers.CompanyName, ClientX.Dashboard.context, ClientX.Customers.Country, ClientX.Customers.CustomerID, ClientX.DatabaseEntities.Customers, ClientX.Dashboard.customerViewSource, ClientX.DatabaseEntities.Orders, ClientX.Dashboard.ordViewSource, ClientX.Customers.PostalCode, ClientX.Customers.Region, and ClientX.Dashboard.ValidateFreight().
ValidateFreight()
decimal? ClientX.Dashboard.ValidateFreight (string freight) inline
Funkcja odpowiadająca za walidację pola Freight oraz konwersję na liczbę dziesiętną
Parameters
freight Pole odpowiadające za wartość opłaty za zamowienie
Returns
Funkcja zwraca liczbę dziesiętną, zwalidowaną i przekonwertowaną z typu string
Definition at line 131 of file Dashboard.xaml.cs.
        {
            decimal validatedFreight;
            decimal freightNew = Convert.ToDecimal(freight);
            if (freightNew > 1)
            {
                validatedFreight = freightNew;
            }
            else
            {
                validatedFreight = 1001;
            }
            return validatedFreight;
        }
Referenced by ClientX.Dashboard.UpdateCommandHandler(), and ClientXTestes.DashboardTests.validateFreight().
Field Documentation
_contentLoaded
bool ClientX.Dashboard._contentLoaded private
Definition at line 435 of file Dashboard.g.cs.
Referenced by ClientX.Dashboard.InitializeComponent().
context
DatabaseEntities ClientX.Dashboard.context = new DatabaseEntities() private
Definition at line 19 of file Dashboard.xaml.cs.
Referenced by ClientX.Dashboard.Delete_Order(), ClientX.Dashboard.DeleteCustomerCommandHandler(), ClientX.Dashboard.Page_Loaded(), ClientX.Dashboard.Search(), and ClientX.Dashboard.UpdateCommandHandler().
customerViewSource
CollectionViewSource ClientX.Dashboard.customerViewSource private
Definition at line 20 of file Dashboard.xaml.cs.
Referenced by ClientX.Dashboard.Dashboard(), ClientX.Dashboard.DeleteCustomerCommandHandler(), ClientX.Dashboard.FirstCommandHandler(), ClientX.Dashboard.LastCommandHandler(), ClientX.Dashboard.NewOrder_click(), ClientX.Dashboard.NextCommandHandler(), ClientX.Dashboard.Page_Loaded(), ClientX.Dashboard.PreviousCommandHandler(), ClientX.Dashboard.Search(), and ClientX.Dashboard.UpdateCommandHandler().
ordViewSource
CollectionViewSource ClientX.Dashboard.ordViewSource private
Definition at line 21 of file Dashboard.xaml.cs.
Referenced by ClientX.Dashboard.Dashboard(), ClientX.Dashboard.Delete_Order(), and ClientX.Dashboard.UpdateCommandHandler().
Property Documentation
ShowAbortMessage
System.Windows.Forms.DialogResult ClientX.Dashboard.ShowAbortMessage static get
Funkcja pomocnicza, pokazująca monit użytkownikowi o anulowaniu wykonywanej operacji
Definition at line 51 of file Dashboard.xaml.cs.
Referenced by ClientX.Dashboard.Delete_Order(), and ClientX.Dashboard.DeleteCustomerCommandHandler().
The documentation for this class was generated from the following files:
Dashboard.xaml.cs
obj/Debug/Dashboard.g.cs
obj/Debug/Dashboard.g.i.cs